version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test 
      POSTGRES_DB: unit-test-user-db
      POSTGRES_PASSWORD: unit-test-pw
    ports: 
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users-db"]
      interval: 5s
      timeout: 10s
      retries: 5
