version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user 
      POSTGRES_DB: users-db
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users-db"]
      interval: 5s
      timeout: 10s
      retries: 5
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
  prometheus:
    image: prom/prometheus
    volumes: 
      - ./otel/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  api:
    image: user:latest
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    # env_file: dev.env
    ports:
      - "50051:50051"
      - "0.0.0.0:8090:8090"
    depends_on: 
     postgres:
       condition: service_healthy
