# environment options: dev, prod
environment: dev
postgres:
  host: localhost
  port: 5432
  db: users-db
  user: user
  password : password
  applicationName: user-service
server:
  host: localhost
  port: 50051
  symmetricKey: 12345678912345678912345678912345
  accessTokenDuration: 10
  refreshTokenDuration: 24
redis:
  host: localhost
  port: 6379
