version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user 
      POSTGRES_DB: users-db
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users-db"]
      interval: 5s
      timeout: 10s
      retries: 5
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  api:
    image: user:latest
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    env_file: dev.env
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on: 
     postgres:
       condition: service_healthy
