version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
  api:
    build:
     context: .
     dockerfile: Dockerfile
    env_file: dev.env
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on: 
      - mongodb
